# Book settings
title: "ThRasE - Thematic Raster Editor"
author: SMByC, IDEAM Colombia
copyright: "2025"
logo: images/thrase.svg

# Enable MyST extensions
parse:
  myst_enable_extensions:
    - deflist
    - html_image

# Force re-execution of notebooks on each build.
execute:
  execute_notebooks: off

# Information about where the book exists on the web.
repository:
  url: https://github.com/SMByC/ThRasE
  path_to_book: docs
  branch: main

html:
  favicon: images/thrase.svg

# Bibliography configuration
bibtex_bibfiles:
  - ../paper/paper.bib

# Sphinx configuration
sphinx:
  extra_extensions:
  - "sphinx.ext.napoleon"
  - "sphinx.ext.viewcode"
  - "sphinxcontrib.bibtex"
  recursive_update: true
  config:
    html_theme_options:
      repository_url: https://github.com/SMByC/ThRasE
      repository_branch: main
      path_to_docs: docs
      secondary_sidebar_items: []  # disable page-toc in sidebar
      # buttons
      use_edit_page_button: true
      use_repository_button: true
      use_download_button: false
      use_fullscreen_button: false
